language: node_js
node_js:
  - stable
script:
  - yarn lint
  - yarn pretty
  - yarn test
  - yarn build
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - trunk
    - release
before_deploy: ./build-tools/before-deploy.sh
deploy:
  - provider: firebase
    on:
      branch: trunk
	    project: $FIREBASE_PROJECT_NIGHTLY

    skip_cleanup: true
    token: $FIREBASE_TOKEN
  - provider: firebase
    on:
      branch: release
	    project: $FIREBASE_PROJECT_STAGING
    skip_cleanup: true
    token: $FIREBASE_TOKEN
